### ISSUE TITLE
Will this work on linux?

### ISSUE THREAD

**Issue by dakshcs** [ForOhForError/Java-Virtual-Greenscreen#1]
I plan to use this program to create a virtual camera source and outputting that to Zoom since zoom for Linux doesn't have a green-screen less-virtual background.

**Comment by dakshshrivastav** [comment]
Also I dont have an nvidia gpu.

**Comment by ForOhForError** [comment]
It should work fine on linux, but I haven't specifically tested for that. The program also only utilizes the CPU at the moment, so it shouldn't matter what GPU you have, or even if you have one.

**Comment by dakshshrivastav** [comment]
Reopen this, it does not work, doesn't show up as an output.

**Comment by ForOhForError** [comment]
"Does not work" is not an issue I can troubleshoot. A full error message, and steps to replicate, is the least amount of information that is workable.

In addition, I have been able to launch the application in the below linux environment; the issue is certainly something in your environment.

```
Ubuntu 20.04.1 LTS

openjdk 11.0.8 2020-07-14

OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)

OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode)

```
